name: Build docs
description: Set-up, gen-doc, sphinx.
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache:  pip
        cache-dependency-path: |
          requirements*.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-docs.txt

    - name: Check environment
      run: |
        pip freeze

    - name: Build base docs
      run: |
        gen-doc schemas/base.yaml -d docs/source/gen-doc --template-directory docs/source/_templates

    - name: Build FileType docs
      run: |
          gen-doc schemas/filetype.yml -d docs/source/gen-doc --template-directory docs/source/_templates

    - name: Build Extractor docs
      run: |
          gen-doc schemas/extractor.yml -d docs/source/gen-doc --template-directory docs/source/_templates

    - name: Upload gen-doc artifact
      uses: actions/upload-artifact@v3
      with:
          name: gen-doc
          path: docs/source/gen-doc

    - name: Build Sphinx docs
      run: |
          sphinx-build -b html docs/source public/main

    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
          name: public-main
          path: public/main


