---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-symlinks
          - id: check-yaml
          - id: check-json
          - id: destroyed-symlinks
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
            name: Fix requirements*.txt
            files: ^requirements.*\.txt$
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            args: [--width, '80']

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.35.1 # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict, -d, '{line-length: {max: 100}}']
