---
name: Check LinkML Schemas
description: Set-up, generate and validate schemas
runs:
    using: composite
    steps:
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
              python-version: '3.10'
              cache: pip
              cache-dependency-path: |
                  requirements*.txt

        - name: Install dependencies
          shell: bash
          run: |
              python -m pip install --upgrade pip
              pip install -U setuptools wheel
              pip install -r requirements.txt

        - name: Check environment
          shell: bash
          run: |
              pip freeze

        - name: Run LinkML generators
          shell: bash
          run: |
              for f in $(ls schemas/*); do
                gen-pydantic -vvv --stacktrace $f
                gen-json-schema -vvv --stacktrace $f
              done

        - name: Validate examples
          shell: bash
          run: |
              for f in $(ls examples/extractor/*.yml); do
                linkml-validate -s schemas/extractor.yml -C Extractor $f
              done

              for f in $(ls examples/filetype/*.yml); do
                linkml-validate -s schemas/filetype.yml -C FileType $f
              done
