---
name: base
version: 0.2.0
id: https://marda-alliance.github.io/metadata_extractors_schema/main/mme_schema/base
prefixes:
    linkml: https://w3id.org/linkml/
    schema_org: http://schema.org/
    dcmitype: http://purl.org/dc/dcmitype/1.1
    dc_terms: http://purl.org/dc/terms/1.1/
    mme_schema: https://marda-alliance.github.io/metadata_extractors_schema/main/mme_schema/
imports:
    - linkml:types
default_range: string
description: >-
    This file describes the generic slots used by models in the MaRDA extractors WG.

classes:
    Citation:
        attributes:
            uri:
                slot_uri: dc_terms:identifier
                required: false
                description: >-
                    An unambiguous reference to the resource within a given context.
                    Recommended practice is to identify the resource by means of a
                    string conforming to an identification system. Examples include
                    International Standard Book Number (ISBN), Digital Object Identifier
                    (DOI), and Uniform Resource Name (URN). Persistent identifiers
                    should be provided as HTTP URIs [from DC].
            creators:
                slot_uri: dc_terms:creator
                multivalued: true
                description: >-
                    A list of the creators of the resource.
            contributors:
                slot_uri: dc_terms:contributor
                multivalued: true
                description: >-
                    A list of the contributors to the resource.
            title:
                required: false
                slot_uri: dc_terms:title
                description: >-
                    A name given to the resource [from DC].
            type:
                required: false
                slot_uri: dc_terms:type
                description: >-
                    Any bibliographic resource type (e.g., article, dataset, software)
                    enumerated in the DCMI Type Vocabulary.
    License:
        attributes:
            uri:
                slot_uri: dc_terms:identifier
                required: false
                description: >-
                    An unambiguous reference to the resource within a given context.
            spdx:
                slot_uri: dc_terms:identifier
                required: false
                description: >-
                    An SPDX License Identifier entry.




slots:
    id:
        identifier: true
        slot_uri: schema_org:identifier
        required: true
        description: >-
            A unique identifier for the entry within the MaRDA
            registry namespace, this should be a shorthand label rather than
            a UUID. Only lower-case alphanumeric and dash ("-") characters
            are permitted.
        pattern: ^[a-z]+[a-z,0-9,-]*[a-z,0-9]+$
    name:
        slot_uri: schema_org:name
        required: true
        description: >-
            A recognisable name for the entry.
    description:
        slot_uri: schema_org:description
        required: true
        description: >-
            A human-readable outline of the entry, its format,
            data content and uses.
    subject:
        slot_uri: dc_terms:subject
        multivalued: true
        description: >-
            Any keywords, phrases or classification codes that are relevant
            to the entry, e.g., particular scientific domains of applicability,
            or experimental techniques.
    citations:
        slot_uri: dcmitype:BibliographicReference
        multivalued: true
        required: false
        range: Citation
        description: >-
            A citation or citations for the entry, to be provided should it be used
            in academic work (or otherwise).
    license:
        slot_uri: dc_terms:license
        required: true
        range: License
        description: >-
            A URL, URI or SPDX license identifier for a legal document giving
            official permission to do something with the resource.
