name: Build docs
description: Set-up, gen-doc, sphinx.
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/download-artifact@v3
      with:
          name: public-main
          path: public/main

    - uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true


