---
name: Build docs
on:
    workflow_call:

jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
                  cache: pip
                  cache-dependency-path: |
                      requirements*.txt

            - name: Install dependencies
              shell: bash
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-docs.txt

            - name: Check environment
              shell: bash
              run: |
                  pip freeze

            - name: Build base docs
              shell: bash
              run: |
                  gen-doc schemas/base.yaml -d docs/source/mme_schema/base --template-directory docs/source/_templates

            - name: Build FileType docs
              shell: bash
              run: |
                  gen-doc schemas/filetype.yml -d docs/source/mme_schema/filetype --template-directory docs/source/_templates  --example-directory examples/filetype

            - name: Build Extractor docs
              shell: bash
              run: |
                  gen-doc schemas/extractor.yml -d docs/source/mme_schema/extractor --template-directory docs/source/_templates --example-directory examples/extractor

            - name: Tar gen-doc files
              run: tar -cvf gen-doc.tar docs/source/mme_schema

            - name: Upload gen-doc artifact
              uses: actions/upload-artifact@v3
              with:
                  name: gen-doc
                  path: gen-doc.tar

            - name: Build Sphinx docs
              shell: bash
              run: |
                  sphinx-build -b html docs/source public/main

            - name: Tar public/main files
              run: tar -cvf public.tar public

            - name: Upload docs artifact
              uses: actions/upload-artifact@v3
              with:
                  name: public.tar
                  path: public.tar
