---
name: Check LinkML schemas
on:
    workflow_call:

jobs:
    check-linkml-schemas:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
                  cache: pip
                  cache-dependency-path: |
                      requirements*.txt

            - name: Install dependencies
              shell: bash
              run: |
                  python -m pip install --upgrade pip
                  pip install -U setuptools wheel
                  pip install -r requirements.txt

            - name: Check environment
              shell: bash
              run: |
                  pip freeze

            - name: Run LinkML generators
              shell: bash
              run: |
                  gen-pydantic -vvv --stacktrace schemas/extractor.yaml
                  gen-json-schema -vvv --stacktrace schemas/extractor.yaml

            - name: Validate examples
              shell: bash
              run: |
                  for f in $(ls examples/Extractor-*.yaml); do
                    linkml-validate -s schemas/extractor.yaml -C Extractor $f
                  done

                  for f in $(ls examples/FileType-*.yaml); do
                    linkml-validate -s schemas/extractor.yaml -C FileType $f
                  done
