---
name: Deploy docs
on:
    workflow_call:

jobs:
    deploy-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - uses: actions/download-artifact@v3
              with:
                  name: public.tar

            - name: run ls
              run: ls -la

            - name: Untar archive
              run: tar -xvf public.tar

            - name: Create index
              run: |
                  echo "<!DOCTYPE html>" > public/index.html
                  echo "<html>" >> public/index.html
                  echo "  <head>" >> public/index.html
                  echo "    <title>Redirecting to main branch</title>" >> public/index.html
                  echo '    <meta charset="utf-8">' >> public/index.html
                  echo '    <meta http-equiv="refresh" content="0; url=./main/index.html">' >> public/index.html
                  echo '    <link rel="canonical" href='https://marda-alliance.github.io/marda_extractors_schema/main/index.html">' >> public/index.html
                  echo "  </head> >> public/index.html
                  echo "</html>" >> public/index.html

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  keep_files: false
