---
name: CI PR

on:
    pull_request:
        branches:
            - main

# Cancel running workflows when additional changes are pushed
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:

    call-check-linkml-schemas:
        uses: ./.github/workflows/check-linkml-schemas.yml

    call-build-docs:
        needs: [call-check-linkml-schemas]
        uses: ./.github/workflows/build-docs.yml

    deploy-pages:
        runs-on: ubuntu-latest
        needs: [call-build-docs]
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - uses: actions/download-artifact@v3
              with:
                  name: public-main
                  path: public.tar

            - uses: Untar archive
              run: tar -xvf public.tar

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  keep_files: true
