---
name: CI PR tests + docs

on:
    pull_request:
        branches:
            - main

# Cancel running workflows when additional changes are pushed
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:

    check-linkml-schemas:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true

            - uses: ./.github/workflows/check-schemas

    build-docs:
        runs-on: windows-latest
        needs: [check-linkml-schemas]
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true

            - uses: ./.github/workflows/build-docs
