---
name: CI main

on:
    push:
        branches:
            - main


jobs:

    call-check-linkml-schemas:
        uses: ./.github/workflows/check-linkml-schemas.yml

    call-build-docs:
        needs: [call-check-linkml-schemas]
        uses: ./.github/workflows/build-docs.yml

    call-deploy-pages:
        needs: [call-build-docs]
        uses: ./.github/workflows/deploy-pages.yml
