---
name: CI main tests + docs + deploy

on:
    push:
        branches:
            - main


jobs:

    call-check-linkml-schemas:
        uses: ./.github/workflows/check-linkml-schemas.yml

    call-build-docs:
        needs: [call-check-linkml-schemas]
        uses: ./.github/workflows/build-docs.yml

    deploy-pages:
        runs-on: ubuntu-latest
        needs: [call-build-docs]
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - uses: actions/download-artifact@v3
              with:
                  name: public-main
                  path: public/main

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  keep_files: true
